import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { sites, news } = JSON.parse(fs.readFileSync(path.join(root, 'src/content.json'), 'utf8'));
const { origin, basePath } = JSON.parse(fs.readFileSync(path.join(root, 'src/config.json'), 'utf8'));
const out = path.join(root, 'dist');
fs.rmSync(out, { recursive: true, force: true });
fs.mkdirSync(out, { recursive: true });
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const prefix = basePath.replace(/\/$/, '');
const url = p => `${prefix}${p}`;
const absolute = p => `${origin}${url(p)}`;
const bySlug = Object.fromEntries(sites.map(s => [s.slug, s]));
const link = s => url(`/sites/${s.slug}/`);
const zoneName = { earth:'Земля', mars:'Марс', prime:'Прайм', space:'Открытый космос', moon:'Луна', phobos:'Фобос' };
const glyph = {earth:'◉',mars:'●',prime:'✝',space:'✦'};
const write = (name, html) => { const target=path.join(out,name); fs.mkdirSync(path.dirname(target),{recursive:true}); fs.writeFileSync(target,html); };

function shell({ title, description, route, body, current='', script='' }) {
  const fullTitle = `${title} — Сеть Одной звезды`;
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(fullTitle)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${absolute(route)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(fullTitle)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${absolute(route)}"><meta name="theme-color" content="#081b2a"><link rel="icon" href="${url('/assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('/assets/style.css')}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:fullTitle,description,url:absolute(route),inLanguage:'ru'})}</script></head><body data-zone="${current}"><div class="shell"><header class="topbar"><a class="wordmark" href="${url('/')}"><span class="mark">✳</span> ОДНА ЗВЕЗДА <span class="muted">/ СЕТЬ</span></a><nav class="toplinks" aria-label="Разделы"><a href="${url('/directory/')}">Каталог</a><a href="${link(bySlug.knowledge)}">Энциклопедия ↗</a></nav></header>${body}<footer><span>ОДНА ЗВЕЗДА · сеть вымышленной Солнечной системы</span><a href="${url('/about/')}">О проекте</a><a href="${url('/directory/')}">Все узлы</a></footer></div>${script ? `<script type="module" src="${url('/assets/app.js')}"></script>` : ''}</body></html>`;
}
function result(s) { return `<article class="result"><a class="domain" href="${link(s)}">${esc(s.domain)} <span>↗</span></a><h3><a href="${link(s)}">${esc(s.title)}</a></h3><p>${esc(s.description)}</p><span class="result-zone">${esc(zoneName[s.zone])}</span></article>`; }
const switches = `<div class="view-switch" role="group" aria-label="Точка обзора">${['earth','mars','prime','space'].map(z=>`<button type="button" data-view="${z}" aria-pressed="false" title="${zoneName[z]}"><span aria-hidden="true">${glyph[z]}</span><span>${zoneName[z]}</span></button>`).join('')}</div>`;
const homeBody = `<main><div class="home-head"><div class="eyebrow">МЕЖПЛАНЕТНАЯ ПОИСКОВАЯ СИСТЕМА <span class="live-dot"></span> СЕТЬ НА СВЯЗИ</div>${switches}</div><section class="hero"><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><div class="hero-inner"><div class="hero-symbol">✳</div><p class="kicker">ВЕСЬ МИР ПОД ОДНОЙ ЗВЕЗДОЙ</p><h1>Найди свой путь<br><em>в Солнечной системе.</em></h1><p class="hero-copy">Публичный индекс планет, станций, кораблей и всего, что между ними.</p><form class="search-form" action="${url('/search/')}" method="get"><label class="sr-only" for="query">Поиск по Сети</label><span class="search-icon" aria-hidden="true">⌕</span><input id="query" name="q" type="search" placeholder="Спросите Сеть или введите адрес…" autocomplete="off" required><button type="submit">НАЙТИ <span>↗</span></button></form><div class="search-hint">ПОПРОБУЙТЕ: <a href="${url('/search/?q=Прайм')}">Прайм</a><a href="${url('/search/?q=Гиперион')}">Гиперион</a><a href="${url('/search/?q=knowledge.wiki')}">knowledge.wiki</a></div></div></section><div class="under-hero"><section class="news-panel"><div class="section-heading"><div><span class="eyebrow">СИГНАЛЫ ИЗ СЕТИ</span><h2 id="news-heading">Межпланетная лента</h2></div><span class="section-index">01 / 02</span></div><div id="news-items">${news.find(n=>n.zone==='space').items.map((n,i)=>`<a class="news-item" href="${link(bySlug[n.site])}"><span class="news-number">0${i+1}</span><span>${esc(n.title)}</span><span class="arrow">↗</span></a>`).join('')}</div></section><aside class="explore-panel"><div class="section-heading"><div><span class="eyebrow">НАЧНИТЕ ОТСЮДА</span><h2>Узлы сети</h2></div><span class="section-index">02 / 02</span></div><a class="feature-link" href="${link(bySlug.knowledge)}"><span class="feature-glyph">◈</span><span><strong>Энциклопедия Солнечной системы</strong><small>knowledge.wiki · путеводитель по миру</small></span><span>↗</span></a><a class="feature-link" href="${url('/directory/')}"><span class="feature-glyph">⌘</span><span><strong>Каталог доменов</strong><small>Планеты, корабли и свободные зоны</small></span><span>↗</span></a><div class="tiny-note">Одна звезда. Множество голосов.<br>Выберите точку обзора, чтобы увидеть свою ленту.</div></aside></div></main>`;
write('index.html', shell({title:'Поиск по Солнечной системе',description:'Вымышленная межпланетная Сеть вселенной «Одна звезда»: поиск, новости Земли, Марса и Прайма, каталог сайтов и энциклопедия.',route:'/',body:homeBody,script:true}));

const searchBody = `<main class="inner-page"><div class="eyebrow">ПОИСК / ПУБЛИЧНЫЙ ИНДЕКС</div><h1>Результаты поиска</h1><form class="search-form inner-search" action="${url('/search/')}" method="get"><label class="sr-only" for="query">Поиск по Сети</label><span class="search-icon" aria-hidden="true">⌕</span><input id="query" name="q" type="search" placeholder="Название, адрес или место" required><button type="submit">НАЙТИ ↗</button></form><div class="filter-row"><span>ПРИОРИТЕТ ПОКАЗА:</span>${switches}</div><p id="search-status" class="search-status">Все узлы публичного индекса</p><div class="result-list" id="results">${sites.map(result).join('')}</div><noscript><p>Для поиска по словам включите JavaScript. Все страницы доступны по ссылкам выше и в <a href="${url('/directory/')}">каталоге</a>.</p></noscript></main>`;
write('search/index.html',shell({title:'Поиск',description:'Поиск по публичному индексу сайтов вымышленной Сети Одной звезды.',route:'/search/',body:searchBody,script:true}));

const zones = [ ['earth','Земля','.ue · .earth · .blue'],['mars','Марс','.x · .mars · .red · .dome · .oai'],['prime','Прайм','.prime · .church · .light · .farm'],['phobos','Фобос','.phobos'],['moon','Луна','.moon'],['space','Свободная Сеть','.xxx · .rum · .hyp · .pirate · .space · .comp · .ship · .base · .news'] ];
const directoryBody = `<main class="inner-page"><div class="eyebrow">КАРТА СЕТИ / ПУБЛИЧНЫЕ АДРЕСА</div><h1>Каталог доменов</h1><p class="lead">Вымышленные домены работают как адреса внутри истории. Здесь у каждого узла есть постоянная страница, доступная в обычном интернете.</p><div class="directory-grid">${zones.map(([zone,name,tlds])=>`<section class="zone-card"><div class="zone-card-top"><span>${esc(name)}</span><span>↗</span></div><div class="tlds">${esc(tlds)}</div><div class="zone-links">${sites.filter(s=>s.zone===zone).map(s=>`<a href="${link(s)}">${esc(s.domain)} <span>↗</span></a>`).join('') || '<span class="muted">Ожидает первых сайтов</span>'}</div></section>`).join('')}</div><p class="directory-note">Зоны задают местонахождение и характер ресурса, но не ограничивают доступ. Поиск видит всю открытую Сеть и меняет порядок результатов в зависимости от выбранной точки обзора.</p></main>`;
write('directory/index.html',shell({title:'Каталог доменов',description:'Зоны и сайты вымышленной Сети Одной звезды: Земля, Марс, Прайм, Луна, Фобос и независимые узлы.',route:'/directory/',body:directoryBody}));

for (const s of sites) {
  const related = s.links.map(slug=>bySlug[slug]).filter(Boolean);
  const body = `<main class="inner-page site-page"><div class="breadcrumb"><a href="${url('/directory/')}">Каталог</a><span>/</span>${esc(zoneName[s.zone])}<span>/</span>${esc(s.domain)}</div><div class="site-mast"><div><div class="eyebrow">${esc(s.tag)}</div><h1>${esc(s.title)}</h1><p class="lead">${esc(s.description)}</p></div><div class="domain-badge"><small>АДРЕС В СЕТИ</small><strong>${esc(s.domain)}</strong><span>ПУБЛИЧНЫЙ УЗЕЛ ●</span></div></div><div class="article-layout"><article class="article-content">${s.body.map(p=>`<p>${esc(p)}</p>`).join('')}</article><aside class="related"><span class="eyebrow">СВЯЗАННЫЕ УЗЛЫ</span>${related.map(r=>`<a href="${link(r)}"><span>${esc(r.title)}</span><small>${esc(r.domain)} ↗</small></a>`).join('')}</aside></div></main>`;
  write(`sites/${s.slug}/index.html`,shell({title:s.title,description:s.description,route:`/sites/${s.slug}/`,body}));
}
const aboutBody = `<main class="inner-page"><div class="eyebrow">О ПРОЕКТЕ</div><h1>Интернет одной звезды</h1><p class="lead">Художественный сетевой слой вселенной «Одна звезда»: страницы, новости и поисковая система, увиденные глазами жителей разных уголков Солнечной системы.</p><div class="article-content"><p>Адреса вроде knowledge.wiki и thechurch.prime существуют внутри вымышленной Сети. В браузере они открываются по настоящим адресам этого сайта. Вы можете читать страницы напрямую, переходить по ссылкам и находить их через обычные поисковики.</p><p>Материалы портала — художественный вымысел. Стартовые записи служат каркасом для будущих историй и могут уточняться по мере развития вселенной.</p><p><a href="${url('/directory/')}">Открыть каталог сети ↗</a></p></div></main>`;
write('about/index.html',shell({title:'О проекте',description:'Как устроена вымышленная Сеть Одной звезды и её каталог доменов.',route:'/about/',body:aboutBody}));

const allRoutes = ['/', '/search/', '/directory/', '/about/', ...sites.map(s=>`/sites/${s.slug}/`)];
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${allRoutes.map(p=>`<url><loc>${absolute(p)}</loc></url>`).join('')}</urlset>`);
write('robots.txt',`User-agent: *\nAllow: /\nSitemap: ${absolute('/sitemap.xml')}\n`);
write('.nojekyll','');
fs.mkdirSync(path.join(out,'assets'),{recursive:true});
for (const asset of ['style.css','app.js','favicon.svg']) fs.copyFileSync(path.join(root,'assets',asset),path.join(out,'assets',asset));
console.log(`Built ${allRoutes.length} pages in dist/`);
