export function renderEarth(site,model,page,{url,absolute,esc},newsItems,story=null) {
  const home=!page && !story;
  const route=story?`/portal.ue/news/${story.slug}/`:page?`/portal.ue/${page.slug}/`:'/portal.ue/';
  const title=story?`${story.title} — Объединённая Земля`:page?`${page.title} — Объединённая Земля`:'Объединённая Земля — официальный портал';
  const description=story?story.summary:page?page.subtitle:site.description;
  const newsLink=item=>url(`/portal.ue/news/${item.slug}/`);
  const nav=`<nav aria-label="Разделы портала"><a class="${home?'active':''}" href="${url('/portal.ue/')}">Главная</a><a class="${page?.slug==='news'||story?'active':''}" href="${url('/portal.ue/news/')}">Новости</a><a class="${page?.slug==='services'?'active':''}" href="${url('/portal.ue/services/')}">Службы</a><a class="${page?.slug==='transit'?'active':''}" href="${url('/portal.ue/transit/')}">Маршруты</a></nav>`;
  const newsRows=newsItems.map((item,i)=>`<a class="ue-news-row" href="${newsLink(item)}"><span class="ue-news-num">0${i+1}</span><span><small>ЗЕМНОЙ СЕГМЕНТ · СООБЩЕНИЕ</small><strong>${esc(item.title)}</strong><em>${esc(item.summary)}</em></span><b>↗</b></a>`).join('');
  const homeBody=`<section class="ue-hero"><div class="ue-hero-copy"><span class="ue-eyebrow">ОФИЦИАЛЬНЫЙ ПОРТАЛ / ПУБЛИЧНЫЙ ДОСТУП</span><h1>Земля. Связь.<br><span>Общее будущее.</span></h1><p>Информация для жителей Объединённой Земли, путешественников и экипажей. Найдите нужную службу, проверьте маршрут и оставайтесь на связи.</p><div class="ue-hero-actions"><a href="${url('/portal.ue/services/')}">Открыть службы <span>↗</span></a><a href="${url('/portal.ue/transit/')}">Маршруты и транспорт →</a></div></div><div class="ue-globe" aria-hidden="true"><div class="ue-globe-core">◉</div><span>UNITED<br>EARTH</span></div></section>
    <section class="ue-population"><div><span class="ue-eyebrow">НАСЕЛЕНИЕ ОБЪЕДИНЁННОЙ ЗЕМЛИ</span><h2 id="population-count" aria-label="Текущая оценка населения">42 381 204 117</h2><p>Оценка меняется в реальном времени</p></div><div class="ue-population-mark"><span class="ue-live-dot"></span> ТЕКУЩИЕ ДАННЫЕ<br><small>ЗЕМНОЙ СЕГМЕНТ СЕТИ</small></div></section>
    <section class="ue-services"><div class="ue-section-intro"><span class="ue-eyebrow">БЫСТРЫЙ ДОСТУП</span><h2>Чем мы можем помочь?</h2></div><div class="ue-service-links"><a href="${url('/portal.ue/services/')}"><span>01</span><strong>Службы и обращения</strong><small>Справочник публичных служб</small><b>↗</b></a><a href="${url('/portal.ue/transit/')}"><span>02</span><strong>Транспорт и маршруты</strong><small>Для путешественников и экипажей</small><b>↗</b></a><a href="${url('/knowledge.wiki/earth/')}"><span>03</span><strong>О Земле</strong><small>Энциклопедия Солнечной системы</small><b>↗</b></a></div></section>
    <section class="ue-news"><div class="ue-news-heading"><div><span class="ue-eyebrow">ПОСЛЕДНИЕ СООБЩЕНИЯ</span><h2>Новости Земли</h2></div><a href="${url('/portal.ue/news/')}">Все новости ↗</a></div><div class="ue-news-list">${newsRows}</div></section><section class="ue-banner"><div><span class="ue-eyebrow">ЕДИНАЯ СЕТЬ</span><h2>От Земли до внешних рубежей.</h2><p>Открытые данные, маршруты и знания доступны из любой точки Солнечной системы.</p></div><a href="${url('/knowledge.wiki/')}">Перейти в энциклопедию ↗</a></section>`;
  const storyBody=story?`<article class="ue-article"><div class="ue-breadcrumb"><a href="${url('/portal.ue/')}">Главная</a> / <a href="${url('/portal.ue/news/')}">Новости</a> / Сообщение</div><span class="ue-eyebrow">ЗЕМНОЙ СЕГМЕНТ · ПУБЛИЧНОЕ СООБЩЕНИЕ</span><h1>${esc(story.title)}</h1><p class="ue-lead">${esc(story.summary)}</p><div class="ue-prose">${story.body.map(p=>`<p>${esc(p)}</p>`).join('')}</div><a class="ue-back" href="${url('/portal.ue/news/')}">← Все новости Земли</a></article>`:'';
  const pageBody=page?`<section class="ue-interior"><div class="ue-breadcrumb"><a href="${url('/portal.ue/')}">Главная</a> / ${esc(page.title)}</div><span class="ue-eyebrow">ОБЪЕДИНЁННАЯ ЗЕМЛЯ · ОТКРЫТЫЙ РАЗДЕЛ</span><h1>${esc(page.title)}</h1><p class="ue-lead">${esc(page.subtitle)}</p>${page.slug==='news'?`<div class="ue-news-list">${newsRows}</div>`:`<div class="ue-prose">${page.body.map(p=>`<p>${esc(p)}</p>`).join('')}</div>`}</section>`:'';
  const schema={'@context':'https://schema.org','@type':story?'NewsArticle':'WebPage',name:title,description,url:absolute(route),inLanguage:'ru'};
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${absolute(route)}"><meta property="og:type" content="${story?'article':'website'}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${absolute(route)}"><link rel="icon" href="${url('/assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('/assets/earth.css')}"><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><div class="ue-network"><a href="${url('/')}">✳ Поиск по Сети Одной звезды</a><span>portal.ue</span></div><div class="ue-official"><span class="ue-seal">◎</span> ОФИЦИАЛЬНЫЙ РЕСУРС ОБЪЕДИНЁННОЙ ЗЕМЛИ <span class="ue-official-right">ОТКРЫТЫЙ ДОСТУП ●</span></div><header class="ue-header"><a class="ue-brand" href="${url('/portal.ue/')}"><span class="ue-brand-symbol">◎</span><span>ОБЪЕДИНЁННАЯ<br>ЗЕМЛЯ<small>ПУБЛИЧНЫЙ ПОРТАЛ</small></span></a>${nav}</header><main>${home?homeBody:story?storyBody:pageBody}</main><footer class="ue-footer"><div><span class="ue-brand-symbol">◎</span><strong>ОБЪЕДИНЁННАЯ ЗЕМЛЯ</strong><p>Публичный портал земного сегмента Сети.</p></div><nav><a href="${url('/portal.ue/news/')}">Новости</a><a href="${url('/portal.ue/services/')}">Службы</a><a href="${url('/portal.ue/transit/')}">Маршруты</a><a href="${url('/')}">Вернуться в Сеть ↗</a></nav></footer>${home?`<script src="${url('/assets/earth.js')}" defer></script>`:''}</body></html>`;
}
