import { forumCategories } from './forum.js';

export function renderForum(site, section, thread, view, {url,absolute,esc}, pageNumber=1) {
  const root=`/${site.domain}/`;
  const sectionPath=s=>`${root}${s.slug}/`;
  const threadPath=(s,t)=>`${sectionPath(s)}${t.slug}/`;
  const route=view==='home'?root:view==='login'||view==='register'?`${root}${view}/`:view==='unavailable'?`${threadPath(section,thread)}page/${pageNumber}/`:thread?threadPath(section,thread):sectionPath(section);
  const title=view==='unavailable'?`Страница ${pageNumber} недоступна — ${thread.title}`:thread?`${thread.title} — Форум «Война и Любовь на Венере»`:section?`${section.title} — Форум «Война и Любовь на Венере»`:view==='login'?'Вход — Война и Любовь на Венере':view==='register'?'Регистрация — Война и Любовь на Венере':'Форум «Война и Любовь на Венере»';
  const desc=thread?`Обсуждение сериала: ${thread.title}`:section?section.description:'Фанатский форум сериала «Война и Любовь на Венере». Обсуждения Джулии, Макса и будущих серий.';
  const breadcrumb=`<div class="bb-crumb"><a href="${url(root)}">Главная форума</a>${section?` <span>›</span> <a href="${url(sectionPath(section))}">${esc(section.title)}</a>`:''}${thread?` <span>›</span> ${esc(thread.title)}`:''}</div>`;
  const row=(s,t)=>`<div class="bb-topic-row"><span class="bb-topic-icon ${t.slug==='rules'?'pinned':''}">${t.slug==='rules'?'✦':'✉'}</span><div class="bb-topic-title"><a href="${url(threadPath(s,t))}">${esc(t.title)}</a>${t.slug==='rules'?'<small>Объявление · закреплено</small>':`<small>Автор: ${esc(t.author)}${t.archive?` · ${t.archive.pages} страниц`:''}</small>`}</div><div class="bb-stat">${(t.archive?.totalPosts??t.posts.length)-1}<small>ответов</small></div><div class="bb-last">${esc(t.archive?.lastUser??t.posts.at(-1).user)}<small>последнее сообщение</small></div></div>`;
  const forumRow=s=>`<div class="bb-forum-row"><span class="bb-forum-icon">${s.icon}</span><div class="bb-forum-name"><a href="${url(sectionPath(s))}">${esc(s.title)}</a><small>${esc(s.description)}</small></div><div class="bb-stat">${s.topics.length}<small>тем</small></div><div class="bb-last"><a href="${url(threadPath(s,s.topics.at(-1)))}">${esc(s.topics.at(-1).title)}</a><small>${esc(s.topics.at(-1).posts.at(-1).user)}</small></div></div>`;
  const listHeader=`<div class="bb-table-head"><span>Форум / тема</span><span>Ответы</span><span>Последнее сообщение</span></div>`;
  const homeBody=`${breadcrumb}<div class="bb-welcome"><div><strong>Добро пожаловать!</strong><p>Обсуждаем сериал, спорим о Джулии и Максе и гадаем, что случится дальше. Читайте старые темы, пока мы чиним вход на форум.</p></div><div class="bb-welcome-heart">♥</div></div><div class="bb-section-title">✿ Форумы сообщества</div><div class="bb-table">${listHeader}${forumCategories.map(forumRow).join('')}</div><div class="bb-lower"><div><strong>Кто сейчас на форуме</strong><p>Сейчас форум просматривают гости из разных частей Сети. Вход участников временно недоступен.</p></div><div><strong>Статистика</strong><p>${forumCategories.reduce((n,s)=>n+s.topics.length,0)} тем · ${forumCategories.reduce((n,s)=>n+s.topics.reduce((m,t)=>m+(t.archive?.totalPosts??t.posts.length),0),0)} сообщений · 4 раздела</p></div></div>`;
  const categoryBody=section?`${breadcrumb}<div class="bb-section-title">${section.icon} ${esc(section.title)} <small>${esc(section.description)}</small></div><div class="bb-actions"><button type="button" disabled title="Публикация временно недоступна">Новая тема</button><span>Раздел открыт только для чтения</span></div><div class="bb-table">${listHeader}${section.topics.map(t=>row(section,t)).join('')}</div><div class="bb-actions"><button type="button" disabled>Новая тема</button><a href="${url(root)}">← Все разделы</a></div>`:'';
  const posts=thread?thread.posts.slice(0,10).map((p,i)=>`<article class="bb-post${p.deleted?' bb-post-deleted':''}" id="post-${i+1}"><aside class="bb-author"><strong>${esc(p.user)}</strong><span class="bb-avatar" aria-hidden="true">${esc(p.user.slice(0,1).toUpperCase())}</span><small>${esc(p.role)}<br>Сообщений: ${i===0?'128':'42'}<br>Откуда: ${p.user.includes('Mars')?'Марс':'Сеть'}</small></aside><div class="bb-message"><div class="bb-post-head"><a href="#post-${i+1}">Сообщение #${i+1}</a><span>время отправки сохранено</span></div><p>${esc(p.text)}</p>${p.deleted?'':`<div class="bb-signature">~ ${esc(p.user)} ~</div>`}</div></article>`).join(''):'';
  const pagination=thread?.archive?`<nav class="bb-pagination" aria-label="Страницы темы"><span>Страница 1 из ${thread.archive.pages}</span><strong aria-current="page">1</strong>${[2,3,4].map(n=>`<a href="${url(`${threadPath(section,thread)}page/${n}/`)}">${n}</a>`).join('')}<span aria-hidden="true">…</span><a href="${url(`${threadPath(section,thread)}page/${thread.archive.pages}/`)}">${thread.archive.pages}</a><a href="${url(`${threadPath(section,thread)}page/2/`)}">Следующая →</a></nav>`:'<span>Страница 1 из 1 · только чтение</span>';
  const threadBody=thread?`${breadcrumb}<div class="bb-section-title">${thread.slug==='rules'?'✦':'♥'} ${esc(thread.title)}</div><div class="bb-actions"><button type="button" disabled>Ответить</button>${pagination}</div><div class="bb-thread">${posts}</div><div class="bb-actions"><button type="button" disabled>Ответить</button>${pagination}<a href="${url(sectionPath(section))}">← Назад в раздел</a></div>`:'';
  const unavailableBody=view==='unavailable'?`${breadcrumb}<div class="bb-section-title">Страница ${pageNumber} из ${thread.archive.pages}</div><div class="bb-auth"><div class="bb-error" role="alert"><strong>Ошибка загрузки архива</strong><p>Не удалось открыть страницу ${pageNumber} этой темы. На форуме временные неполадки; старые сообщения пока недоступны. Начало обсуждения можно читать.</p></div><p><a href="${url(threadPath(section,thread))}">← Вернуться к первым 10 сообщениям</a></p></div>`:'';
  const authBody=view==='login'||view==='register'?`${breadcrumb}<div class="bb-section-title">${view==='login'?'Вход на форум':'Регистрация'}</div><div class="bb-auth"><div class="bb-error"><strong>Временные неполадки на сайте</strong><p>Вход, регистрация и публикация сообщений сейчас недоступны. Все разделы и старые обсуждения можно просматривать без учётной записи.</p></div><form><fieldset disabled><label>Имя пользователя<input type="text" autocomplete="off" placeholder="Имя пользователя"></label>${view==='register'?'<label>Адрес для связи<input type="email" placeholder="Адрес для связи"></label>':''}<label>Пароль<input type="password" autocomplete="off" placeholder="Пароль"></label><button type="button">${view==='login'?'Войти':'Зарегистрироваться'}</button></fieldset></form><p><a href="${url(root)}">← Читать форум без входа</a></p></div>`:'';
  const body=view==='unavailable'?unavailableBody:view==='home'?homeBody:thread?threadBody:section?categoryBody:authBody;
  const robots=['login','register','unavailable'].includes(view)?'<meta name="robots" content="noindex">':'';
  const schema={'@context':'https://schema.org','@type':thread&&view!=='unavailable'?'DiscussionForumPosting':'WebPage',name:title,description:desc,url:absolute(route),inLanguage:'ru'};
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title>${robots}<meta name="description" content="${esc(desc)}"><link rel="canonical" href="${absolute(route)}"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><link rel="icon" href="${url('/assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('/assets/forum.css')}"><script type="application/ld+json">${JSON.stringify(schema)}</script></head><body><div class="bb-network"><a href="${url('/')}">✳ Поиск по Сети Одной звезды</a><span>${esc(site.domain)}</span></div><div class="bb-wrap"><header class="bb-banner"><div class="bb-ribbon">★ КЛУБ ПОКЛОННИКОВ СЕРИАЛА ★</div><a href="${url(root)}"><span>♥</span> Война и Любовь <em>на Венере</em></a><p>Обсуждаем любимый сериал всей солнечной системой</p></header><nav class="bb-nav"><a href="${url(root)}">⌂ Главная</a><a href="${url('/knowledge.wiki/')}">◈ Сеть</a><span></span><a href="${url(`${root}login/`)}">Вход</a><a href="${url(`${root}register/`)}">Регистрация</a></nav><div class="bb-notice"><b>⚠ Временные неполадки на сайте.</b> Форум работает только для чтения: вход, регистрация и ответы недоступны.</div><main><h1 class="bb-visually-hidden">${esc(title)}</h1>${body}</main><footer class="bb-footer"><span>Война и Любовь на Венере · фанатский форум</span><a href="${url(root)}">К началу ↑</a><a href="${url('/')}">В Сеть Одной звезды ↗</a></footer></div></body></html>`;
}
