export function renderOlympic(site, model, page, {url,absolute,esc}) {
  const home=!page;
  const route=`/olympic.ship/${home?'':`${page.slug}/`}`;
  const title=home?'Olympic — межпланетный круиз':`${page.title} — Olympic`;
  const description=home?'Круиз на Olympic: Прайм, Гиперион, Сатурн, Марс и Земля. Бассейны, рестораны, каюты и три президентских пентхауса.':page.subtitle;
  const pageURL=slug=>url(`/olympic.ship/${slug}/`);
  const nav=`<nav aria-label="Разделы Olympic"><a class="${home?'active':''}" href="${url('/olympic.ship/')}">Главная</a>${model.pages.map(p=>`<a class="${p===page?'active':''}" href="${pageURL(p.slug)}">${esc(p.title)}</a>`).join('')}</nav>`;
  const stops=[
    ['01','Прайм','Развлечения, экологичный отдых, настоящее пиво и йога.','prime'],
    ['02','Гиперион','Дозаправка и экстремальные приключения для тех, кому мало обычного отдыха.','hyperion'],
    ['03','Сатурн','Подход к планете и наблюдение за её кольцами с обзорных палуб.'],
    ['04','Невесомость','Купание без привычных «верха» и «низа» — отдельное событие на борту.'],
    ['05','Марс','Дюнное сафари, мясо коров особой породы с картофелем и мастер-класс по спирулине.','mars'],
    ['06','Земля · ОЗ','Пляжи Иберии и Сиама — финал маршрута, который хочется продолжить.','ue']
  ];
  const cabins=[
    ['ГОРИЗОНТ','Умный выбор','Уютная каюта и весь Olympic за порогом. Больше впечатлений в портах.'],
    ['ПАНОРАМА','Вид на путешествие','Больше пространства и широкое окно на меняющуюся Солнечную систему.'],
    ['ОРБИТА','Сьют','Отдельная гостиная, спокойствие и приоритетный сервис.'],
    ['ПРЕЗИДЕНТСКИЙ','Всего три','Три частные пентхаус-резиденции с персональным обслуживанием и лучшим обзором.']
  ];
  const homeBody=`<section class="ol-hero"><div class="ol-stars" aria-hidden="true"></div><div class="ol-planet" aria-hidden="true"></div><div class="ol-ship" aria-hidden="true"><div class="ol-ship-top"></div><div class="ol-ship-body"></div><div class="ol-ship-lights"></div></div><div class="ol-hero-copy"><span class="ol-kicker">МЕЖПЛАНЕТНЫЙ КРУИЗ / OLYMPIC</span><h1>Дорога<br><i>продолжается.</i></h1><p>Откройте Солнечную систему с борта гигантского корабля, на котором само путешествие становится лучшей частью отпуска.</p><div class="ol-actions"><a class="ol-button" href="${pageURL('journey')}">Смотреть маршрут <span>↗</span></a><a class="ol-text-link" href="#life">Узнать о жизни на борту ↓</a></div></div><div class="ol-hero-foot"><span>ОДНА ЗВЕЗДА / МНОГО МИРОВ</span><span>ЛИСТАЙТЕ ВНИЗ ↓</span></div></section>
    <section class="ol-intro" id="life"><div class="ol-section-label">01 / КОРАБЛЬ КАК МЕСТО НАЗНАЧЕНИЯ</div><div><h2>Между мирами есть целый мир.</h2><p>Несколько бассейнов, лучшие рестораны, обзорные палубы и места, где можно остаться наедине с космосом. На Olympic найдётся вечер для большого праздника и утро, которое захочется провести в тишине.</p><a href="${pageURL('onboard')}">Исследовать корабль ↗</a></div></section>
    <section class="ol-experience"><div class="ol-feature ol-pool"><span>01 / ОТДЫХ</span><h3>Бассейны<br>между звёздами</h3><p>Вода, свет и вид, который не повторится дважды.</p></div><div class="ol-feature ol-dining"><span>02 / ВКУС</span><h3>Вечер<br>на ваш вкус</h3><p>От неспешного ужина до открытия нового блюда после каждой остановки.</p></div><div class="ol-feature ol-view"><span>03 / ПРОСТРАНСТВО</span><h3>Ваше место<br>у окна</h3><p>Каюты и сьюты для разных способов путешествовать.</p></div></section>
    <section class="ol-cabins" id="cabins"><div class="ol-section-head"><span class="ol-section-label">02 / РАЗМЕЩЕНИЕ</span><h2>Каюта под ваш<br><i>масштаб мечты.</i></h2><p>От доступной каюты до частной резиденции — разные уровни и цены. Один и тот же космос за окном.</p></div><div class="ol-cabin-grid">${cabins.map((c,i)=>`<a class="ol-cabin ${i===3?'ol-penthouse':''}" href="${pageURL('cabins')}"><span>0${i+1} / ${c[0]}</span><h3>${c[1]}</h3><p>${c[2]}</p><b>УЗНАТЬ БОЛЬШЕ ↗</b></a>`).join('')}</div><div class="ol-cabins-foot">Три президентских пентхауса. Ни одного одинакового вида из окна.</div></section>
    <section class="ol-route" id="route"><div class="ol-section-head"><span class="ol-section-label">03 / МАРШРУТ</span><h2>Шесть глав.<br><i>Одна история.</i></h2><p>От тихого утра на Прайме до пляжей Земли — с Сатурном посередине.</p></div><div class="ol-stops">${stops.map(([n,name,desc])=>`<div class="ol-stop"><span>${n}</span><h3>${esc(name)}</h3><p>${esc(desc)}</p></div>`).join('')}</div><a class="ol-route-link" href="${pageURL('journey')}">Весь маршрут и впечатления <span>↗</span></a></section>
    <section class="ol-captain"><div class="ol-captain-portrait" aria-hidden="true"><span>JR</span><small>COMMANDER / OLYMPIC</small></div><div><span class="ol-section-label">04 / ПРИГЛАШЕНИЕ НА БОРТ</span><blockquote>«Я буду рада видеть вас на Olympic. Выберите каюту, оставьте привычное за шлюзом и позвольте этому путешествию вас удивить».</blockquote><p><strong>Дженна Реджис</strong><br>командир Olympic</p></div></section>
    <section class="ol-end"><span>ВАШЕ СЛЕДУЮЩЕЕ ПУТЕШЕСТВИЕ</span><h2>Дорога продолжается.<br>Вы с нами?</h2><div><a class="ol-button" href="${pageURL('cabins')}">Выбрать уровень каюты ↗</a><a class="ol-text-link" href="${pageURL('journey')}">Смотреть маршрут →</a></div></section>`;
  const subBody=page?`<div class="ol-subpage"><div class="ol-breadcrumb"><a href="${url('/olympic.ship/')}">OLYMPIC</a> / ${esc(page.title)}</div><span class="ol-kicker">${esc(model.eyebrow)}</span><h1>${esc(page.title)}</h1><p class="ol-subtitle">${esc(page.subtitle)}</p>${page.slug==='cabins'?`<div class="ol-cabin-grid">${cabins.map((c,i)=>`<article class="ol-cabin ${i===3?'ol-penthouse':''}"><span>0${i+1} / ${c[0]}</span><h2>${c[1]}</h2><p>${c[2]}</p></article>`).join('')}</div>`:page.slug==='journey'?`<div class="ol-stops ol-stops-detail">${stops.map(([n,name,desc])=>`<article class="ol-stop"><span>${n}</span><h2>${esc(name)}</h2><p>${esc(desc)}</p></article>`).join('')}</div>`:`<div class="ol-onboard-grid"><article><span>01 / ВОДА</span><h2>Несколько бассейнов</h2><p>Найдите свой ритм: от спокойного утра у воды до вечера под светом обзорной палубы.</p></article><article><span>02 / ВКУС</span><h2>Рестораны</h2><p>Разные кухни и разные поводы задержаться за столом. На Olympic ужин — часть маршрута.</p></article><article><span>03 / ВИД</span><h2>Обзорные палубы</h2><p>Солнечная система меняется за окном. У вас есть время увидеть её без спешки.</p></article></div>`}<div class="ol-next"><a href="${url('/olympic.ship/')}">← Вернуться на главную Olympic</a><a href="${pageURL(page.slug==='cabins'?'journey':'cabins')}">${page.slug==='cabins'?'Посмотреть маршрут':'Выбрать каюту'} →</a></div></div>`:'';
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${absolute(route)}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${absolute(route)}"><link rel="icon" href="${url('/assets/favicon.svg')}" type="image/svg+xml"><link rel="stylesheet" href="${url('/assets/olympic.css')}"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'WebPage',name:title,description,url:absolute(route),inLanguage:'ru'})}</script></head><body><div class="ol-network"><a href="${url('/')}">✳ Поиск по Сети Одной звезды</a><span>olympic.ship</span></div><div class="ol-frame"><header class="ol-header"><a class="ol-brand" href="${url('/olympic.ship/')}">OLYMPIC / LOG</a>${nav}</header><main>${home?homeBody:subBody}</main><footer class="ol-footer"><span>OLYMPIC / LOG <small>· olympic.ship</small></span><div><a href="${url('/olympic.ship/')}">Главная</a><a href="${url('/')}">Вернуться в Сеть ↗</a></div></footer></div></body></html>`;
}
